### ISSUE TITLE
Support XLA for both torch and tensorflow

### ISSUE THREAD

**Issue by diegofiori** [nebuly-ai/nebullvm#121]
# Description

Currently nebullvm does not support TF-built in compiler XLA, which also allows the model to be compiled on Google TPUs. XLA is available for JAX, TF and PyTorch. Details about the TensorFlow and PyTorch implementations can be found in the following links:

- [XLA for PyTorch](https://pytorch.org/xla/release/1.13/index.html)
- [XLA for Tensorflow](https://www.tensorflow.org/xla)

# Integration

We should implement two new classes in nebullvm both inheriting from `Compiler`. They should implement the interfaces for PyTorch and TensorFlow of the XLA compiler. Note that XLA also supports reduced precision, so the quantization types must be managed too. For inspiration while coding the class interface you can analyse the `Compiler`s built on top of TensorRT.

Note that XLA performance should be tested on a TPU for accessing its real performance.

# TODO list

- [ ]  Implement a PoC of the feature on Colab
- [ ]  If not available a TPU, ping @valeriosofi for running the final version of the Colab notebook on Nebuly’s GCP account (Note that the debugging can be performed by yourself using other HW devices).
- [ ]  Analyse the impact of the feature respect the actual AutoBoost
- [ ]  If a positive impact of the feature is assessed we should implement it as a Compiler object else send your results to v.sofi@nebuly.ai detailing your findings and explaining why we should not proceed with the implementation of the feature
- [ ]  Fork the nebullvm repo https://github.com/nebuly-ai/nebullvm
- [ ]  Read the [Contribution Guidelines](https://github.com/nebuly-ai/nebullvm/blob/main/CONTRIBUTING.md)
- [ ]  Create a PR to main explaining your changes and showing the improvements obtained with the XLA compilers respect the previous versions

**Comment by comidan** [comment]
I'm gonna do it! 😁

**Comment by valeriosofi** [comment]
Hi @comidan, any news about this feature implementation? :)
