### ISSUE TITLE
Add multiple sources for generating synthetic data

### ISSUE THREAD

**Issue by diegofiori** [nebuly-ai/nebullvm#221]
# Description

Currently, chatllama supports the synthetic data generation just from OpenAI’s `davinci-003`. In order to avoid huge costs while generating data we should support  other API models (as the cheaper `gpt-3.5-turbo` ), other API providers and local models (Flan T5 seems a good candidate).

Furthermore, in order to generate more diverse data, it could be beneficial to be able to use multiple prompt templates during the generation.

# TODO

- [ ]  Add support for `gpt-3.5-turbo` . Externally respect to LangChain models
- [ ]  Modify langchain-based script for supporting multiple API models and providers
- [x]  Add support for HF models in dataset generation.
- [ ]  Allow user to specify multiple templates when generating synthetic data
- [ ]  Provide multiple template examples for dataset generation.

**Comment by pengwei-iie** [comment]
hi did you add support for HF models in dataset generation? It seems only OpenAI’s davinci-003 in line 21 in generate_rewards.py.
