### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by diegofiori** [nebuly-ai/nebullvm#222]
# Description

Currently ChatLLaMA documentation consists of just the readme on github. We should align chatllama with the other modules in nebullvm and add the `mkdocs`  documentation to `docs.nebuly.com`. 

All documentation must be written in markdown format and put into a docs folder in the chatllama repo.

The documentation should give more details on both the model supported and on the dataset generation. In particular, on the dataset generation side we need to add more examples of usage and explain in more details the advantages of the different approaches.

We must put a section on the training on multiple-gpus. In articular we should explain how to properly use deep-speed and configure it for training the model.

# TODO

- [ ]  Add documentation in the docs folder.
- [ ]  Build the docs with mkdocs
- [ ]  Push the new docs in `docs.nebuly.com`
