### ISSUE TITLE
Implement optimized inference for ChatLLaMA

### ISSUE THREAD

**Issue by diegofiori** [nebuly-ai/nebullvm#223]
# Description

ChatLLaMA currently does not have either a playground or some scripts which allow the user to easily use the model for inference. It would be great to add a package for chatllama inference for efficiently loading chatllama in production. Note that it would be amazing to also provide some prompt templates for getting chat-like experience directly from the not fine-tuned LLaMA models.

# TODO

- [ ]  Add DeepSpeed Inference support to LLaMA model
- [ ]  Support Flexgen for maximizing throughput
- [ ]  Add support to Accelerate
- [ ]  Implement a playground UI using GRADIO supporting multi-gpu deployment.
- [ ]  Add prompts example for testing LLaMA as a chatbot before running RLHF training
